php:
  preset: laravel
  disabled:
    - unused_use
  enabled:
    - align_double_arrow
  finder:
    not-name:
      - index.php
      - server.php
js:
  finder:
    not-name:
      - webpack.mix.js
css: true
