language: php

php:
  - 7.3
  - 7.4

services:
  - mysql

before_script:
  - cp .env.travis .env
  - mysql -u root -e 'create database laravelAuth;'
  - composer self-update
  - composer install --no-interaction
  - php artisan vendor:publish --tag=laravelroles
  - php artisan vendor:publish --tag=laravel2step
  - php artisan key:generate
  - php artisan migrate:install --env=testing --no-interaction
  - composer dump-autoload
  - sudo chgrp -R www-data storage bootstrap/cache
  - sudo chmod -R ug+rwx storage bootstrap/cache
  - php artisan migrate
  - php artisan db:seed
